"""
dl_pipeline/train.py
====================
Imitation Learning Training Loop

The Transformer learns to imitate the optimal phase decisions
generated by SUMO's built-in actuated controller (or our
synthetic optimal labels from the queuing model).

Training = supervised multi-class classification.
  Loss: CrossEntropy(predicted_phase, optimal_phase_label)
  Metric: Top-1 accuracy on test set

Why this approach is defensible:
  "Behavioral cloning for traffic signal control is a published,
  cited approach (ITSC 2020). We train to imitate an optimal oracle
  controller, then deploy the learned policy online. This decouples
  data generation (SUMO) from policy learning (Transformer) and
  produces interpretable loss curves — critical for a 15-day project."
"""

import os
import sys
import json
import time
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
import numpy as np

sys.path.append(os.path.dirname(os.path.dirname(__file__)))
from dl_pipeline.transformer import LaneAwareAttentionNetwork
from data_gen.dataset import get_dataloaders
from configs.config import MODEL


def train_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss = correct = total = 0
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out["logits"], y)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), MODEL.grad_clip)
        optimizer.step()
        total_loss += loss.item() * len(y)
        correct += (out["logits"].argmax(1) == y).sum().item()
        total += len(y)
    return total_loss / total, correct / total


@torch.no_grad()
def eval_epoch(model, loader, criterion, device):
    model.eval()
    total_loss = correct = total = 0
    all_preds, all_labels = [], []
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        out = model(x)
        loss = criterion(out["logits"], y)
        total_loss += loss.item() * len(y)
        preds = out["logits"].argmax(1)
        correct += (preds == y).sum().item()
        total += len(y)
        all_preds.extend(preds.cpu().tolist())
        all_labels.extend(y.cpu().tolist())
    return total_loss / total, correct / total, all_preds, all_labels


def per_phase_accuracy(preds, labels, n_phases=4):
    """Per-phase accuracy for the results table."""
    accs = {}
    for p in range(n_phases):
        idx = [i for i, l in enumerate(labels) if l == p]
        if not idx:
            accs[p] = 0.0
            continue
        accs[p] = sum(preds[i] == labels[i] for i in idx) / len(idx)
    return accs


def train(
    csv_path: str = "data/traffic_dataset.csv",
    use_two_wheeler: bool = True,
    run_id: str = None,
    device: str = None,
) -> dict:
    """
    Full training run. Returns history dict.

    Args:
        use_two_wheeler: If False, zeroes out feature index 4
                         (two_wheeler_ratio) for ablation study.
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    if run_id is None:
        run_id = "full" if use_two_wheeler else "ablation"

    print(f"\n{'='*55}")
    print(f"Training LAAN | mode={run_id} | device={device}")
    print(f"{'='*55}")

    os.makedirs(MODEL.checkpoint_dir, exist_ok=True)
    train_loader, val_loader, test_loader = get_dataloaders(csv_path)
    model = LaneAwareAttentionNetwork().to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(
        model.parameters(),
        lr=MODEL.learning_rate,
        weight_decay=MODEL.weight_decay,
    )
    scheduler = CosineAnnealingLR(optimizer, T_max=MODEL.n_epochs, eta_min=1e-5)

    # Hook to zero out two_wheeler_ratio during ablation
    hook = None
    if not use_two_wheeler:
        def _zero_tw(module, inp):
            x = inp[0].clone()
            x[:, :, 4] = 0.0   # feature index 4 = two_wheeler_ratio
            return (x,) + inp[1:]
        hook = model.input_proj.register_forward_pre_hook(_zero_tw)

    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}
    best_val_acc = 0.0
    patience_ctr = 0
    best_path = MODEL.best_model_path if use_two_wheeler else MODEL.ablation_model_path

    t0 = time.time()
    for epoch in range(1, MODEL.n_epochs + 1):
        tr_loss, tr_acc = train_epoch(model, train_loader, optimizer, criterion, device)
        vl_loss, vl_acc, _, _ = eval_epoch(model, val_loader, criterion, device)
        scheduler.step()

        history["train_loss"].append(tr_loss)
        history["val_loss"].append(vl_loss)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(vl_acc)

        if vl_acc > best_val_acc:
            best_val_acc = vl_acc
            patience_ctr = 0
            torch.save({"epoch": epoch, "state": model.state_dict(),
                        "val_acc": vl_acc}, best_path)
        else:
            patience_ctr += 1

        if epoch % 5 == 0 or epoch == 1:
            print(f"  Ep {epoch:3d}/{MODEL.n_epochs} | "
                  f"tr_loss={tr_loss:.4f} tr_acc={tr_acc:.3f} | "
                  f"vl_loss={vl_loss:.4f} vl_acc={vl_acc:.3f}")

        if patience_ctr >= MODEL.patience:
            print(f"  Early stop at epoch {epoch}.")
            break

    # Final test evaluation
    ckpt = torch.load(best_path, map_location=device)
    model.load_state_dict(ckpt["state"])
    test_loss, test_acc, preds, labels = eval_epoch(model, test_loader, criterion, device)
    phase_accs = per_phase_accuracy(preds, labels)

    if hook:
        hook.remove()

    print(f"\n  Test accuracy: {test_acc:.4f} | Time: {time.time()-t0:.0f}s")
    print(f"  Per-phase accuracy: { {k: f'{v:.3f}' for k,v in phase_accs.items()} }")

    history.update({
        "test_acc": test_acc, "test_loss": test_loss,
        "best_val_acc": best_val_acc, "phase_accs": phase_accs,
    })

    out_path = f"data/training_history_{run_id}.json"
    with open(out_path, "w") as f:
        json.dump(history, f, indent=2)
    print(f"  History saved: {out_path}")

    return history


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--ablation", action="store_true")
    args = p.parse_args()
    train(use_two_wheeler=not args.ablation)
